const FOODS = [
  { id: "chicken", name: "Куриная грудка", cat: "Мясо", kcal: 165, p: 31, f: 3.6, c: 0 },
  { id: "chicken-thigh", name: "Бедро куриное без кожи", cat: "Мясо", kcal: 177, p: 19, f: 11, c: 0 },
  { id: "chicken-wing", name: "Крылья куриные", cat: "Мясо", kcal: 186, p: 19, f: 12, c: 0 },
  { id: "chicken-grill", name: "Цыплёнок гриль", cat: "Мясо", kcal: 237, p: 27, f: 13.5, c: 0 },
  { id: "chicken-fillet-baked", name: "Филе грудки запечённое", cat: "Мясо", kcal: 148, p: 29, f: 3.2, c: 0.5 },
  { id: "turkey", name: "Индейка филе", cat: "Мясо", kcal: 135, p: 29, f: 2, c: 0 },
  { id: "turkey-sausage", name: "Сосиски из индейки", cat: "Колбасы", kcal: 196, p: 13, f: 15, c: 2 },
  { id: "beef", name: "Говядина", cat: "Мясо", kcal: 187, p: 26, f: 9, c: 0 },
  { id: "beef-stew", name: "Говядина тушёная", cat: "Мясо", kcal: 232, p: 17, f: 18, c: 0 },
  { id: "pork", name: "Свинина нежирная", cat: "Мясо", kcal: 160, p: 21, f: 8, c: 0 },
  { id: "pork-neck", name: "Шея свиная", cat: "Мясо", kcal: 267, p: 16, f: 22, c: 0 },
  { id: "mince", name: "Фарш говяжий", cat: "Мясо", kcal: 254, p: 17, f: 20, c: 0 },
  { id: "mince-home", name: "Фарш домашний", cat: "Мясо", kcal: 263, p: 17, f: 21, c: 0 },
  { id: "mince-chicken", name: "Фарш куриный", cat: "Мясо", kcal: 143, p: 17, f: 8, c: 0 },
  { id: "liver", name: "Печень говяжья", cat: "Мясо", kcal: 135, p: 20, f: 4, c: 4 },
  { id: "liver-chicken", name: "Печень куриная", cat: "Мясо", kcal: 136, p: 20, f: 6, c: 0.8 },
  { id: "heart-chicken", name: "Сердце куриное", cat: "Мясо", kcal: 159, p: 16, f: 10, c: 0.8 },
  { id: "rabbit", name: "Кролик", cat: "Мясо", kcal: 156, p: 21, f: 8, c: 0 },
  { id: "cutlet-chicken", name: "Котлета куриная", cat: "Мясо", kcal: 220, p: 15, f: 14, c: 9 },
  { id: "schnitzel", name: "Шницель куриный", cat: "Готовая еда", kcal: 210, p: 18, f: 12, c: 8 },

  { id: "doctor", name: "Колбаса докторская", cat: "Колбасы", kcal: 257, p: 13, f: 22, c: 1.5 },
  { id: "sausage-milk", name: "Сосиски молочные", cat: "Колбасы", kcal: 266, p: 10, f: 24, c: 1.6 },
  { id: "sardelki", name: "Сардельки", cat: "Колбасы", kcal: 296, p: 10, f: 28, c: 1.5 },
  { id: "ham", name: "Ветчина", cat: "Колбасы", kcal: 145, p: 18, f: 8, c: 0.5 },
  { id: "carbonade", name: "Карбонад", cat: "Колбасы", kcal: 135, p: 16, f: 8, c: 0 },
  { id: "servelat", name: "Сервелат", cat: "Колбасы", kcal: 421, p: 24, f: 36, c: 0.2 },
  { id: "salami", name: "Салями", cat: "Колбасы", kcal: 568, p: 21, f: 53, c: 1.4 },
  { id: "sausage-half", name: "Колбаса полукопчёная", cat: "Колбасы", kcal: 380, p: 17, f: 34, c: 0.3 },
  { id: "pate", name: "Паштет печёночный", cat: "Колбасы", kcal: 301, p: 12, f: 28, c: 3 },
  { id: "carpaccio", name: "Карпаччо из индейки", cat: "Колбасы", kcal: 118, p: 22, f: 3, c: 0.5 },
  { id: "holodets", name: "Холодец", cat: "Готовая еда", kcal: 80, p: 16, f: 1.5, c: 0.3 },

  { id: "salmon", name: "Лосось / сёмга", cat: "Рыба", kcal: 208, p: 20, f: 13, c: 0 },
  { id: "salmon-weak", name: "Сёмга слабосолёная", cat: "Рыба", kcal: 202, p: 23, f: 12, c: 0 },
  { id: "tuna", name: "Тунец", cat: "Рыба", kcal: 132, p: 28, f: 1, c: 0 },
  { id: "tuna-can", name: "Тунец в собственном соку", cat: "Рыба", kcal: 96, p: 21, f: 1, c: 0 },
  { id: "cod", name: "Треска", cat: "Рыба", kcal: 82, p: 18, f: 0.7, c: 0 },
  { id: "pollock", name: "Минтай", cat: "Рыба", kcal: 72, p: 16, f: 0.9, c: 0 },
  { id: "hake", name: "Хек", cat: "Рыба", kcal: 86, p: 16, f: 2.2, c: 0 },
  { id: "keta", name: "Кета", cat: "Рыба", kcal: 127, p: 19, f: 5.6, c: 0 },
  { id: "mackerel", name: "Скумбрия", cat: "Рыба", kcal: 205, p: 18, f: 14, c: 0 },
  { id: "herring", name: "Сельдь солёная", cat: "Рыба", kcal: 217, p: 17, f: 16, c: 0 },
  { id: "sprats", name: "Шпроты в масле", cat: "Рыба", kcal: 363, p: 17, f: 32, c: 0 },
  { id: "shrimp", name: "Креветки", cat: "Рыба", kcal: 99, p: 24, f: 0.3, c: 0.2 },
  { id: "squid", name: "Кальмар", cat: "Рыба", kcal: 100, p: 18, f: 2.2, c: 2 },
  { id: "crab-sticks", name: "Крабовые палочки", cat: "Рыба", kcal: 73, p: 6, f: 0.5, c: 11 },
  { id: "fish-sticks", name: "Рыбные палочки", cat: "Заморозка", kcal: 240, p: 13, f: 12, c: 20 },

  { id: "egg", name: "Яйцо куриное", cat: "Молочное", kcal: 157, p: 13, f: 11, c: 1.1, unit: "шт", unitG: 55 },
  { id: "egg-c0", name: "Яйцо С0 отборное", cat: "Молочное", kcal: 157, p: 13, f: 11, c: 1.1, unit: "шт", unitG: 65 },
  { id: "cottage", name: "Творог 5%", cat: "Молочное", kcal: 121, p: 17, f: 5, c: 1.8 },
  { id: "cottage0", name: "Творог 0%", cat: "Молочное", kcal: 71, p: 16, f: 0.2, c: 1.8 },
  { id: "cottage18", name: "Творог 9%", cat: "Молочное", kcal: 159, p: 16, f: 9, c: 3 },
  { id: "cottage-soft", name: "Творог мягкий 0.1%", cat: "Молочное", kcal: 70, p: 13, f: 0.1, c: 4 },
  { id: "cottage-protein", name: "Творог высокобелковый", cat: "ЗОЖ", kcal: 90, p: 18, f: 0.5, c: 3.3 },
  { id: "yogurt", name: "Йогурт натуральный", cat: "Молочное", kcal: 66, p: 5, f: 3.2, c: 4.7 },
  { id: "yogurt-fruit", name: "Йогурт фруктовый", cat: "Молочное", kcal: 89, p: 3.2, f: 2.5, c: 13 },
  { id: "skyr", name: "Скир", cat: "ЗОЖ", kcal: 63, p: 11, f: 0.2, c: 4 },
  { id: "skyr-apple", name: "Скир с печёным яблоком", cat: "ЗОЖ", kcal: 78, p: 9, f: 0.3, c: 10 },
  { id: "greek", name: "Йогурт греческий 2%", cat: "Молочное", kcal: 73, p: 9, f: 2, c: 4 },
  { id: "kefir", name: "Кефир 2.5%", cat: "Молочное", kcal: 50, p: 3, f: 2.5, c: 4 },
  { id: "kefir1", name: "Кефир 1%", cat: "Молочное", kcal: 40, p: 3, f: 1, c: 4 },
  { id: "ryazhenka", name: "Ряженка 4%", cat: "Молочное", kcal: 67, p: 3, f: 4, c: 4.2 },
  { id: "smetana15", name: "Сметана 15%", cat: "Молочное", kcal: 158, p: 2.6, f: 15, c: 3 },
  { id: "smetana20", name: "Сметана 20%", cat: "Молочное", kcal: 206, p: 2.8, f: 20, c: 3.2 },
  { id: "smetana10", name: "Сметана 10%", cat: "Молочное", kcal: 115, p: 3, f: 10, c: 2.9 },
  { id: "milk", name: "Молоко 2.5%", cat: "Молочное", kcal: 52, p: 2.8, f: 2.5, c: 4.7 },
  { id: "milk32", name: "Молоко 3.2%", cat: "Молочное", kcal: 60, p: 2.9, f: 3.2, c: 4.7 },
  { id: "milk05", name: "Молоко 0.5%", cat: "Молочное", kcal: 35, p: 3, f: 0.5, c: 4.9 },
  { id: "prostokvasha", name: "Простокваша", cat: "Молочное", kcal: 58, p: 2.8, f: 3.2, c: 4.1 },
  { id: "ayran", name: "Айран", cat: "Напитки", kcal: 27, p: 1.5, f: 1, c: 2.5 },
  { id: "tan", name: "Тан", cat: "Напитки", kcal: 20, p: 1.1, f: 0.5, c: 2.2 },
  { id: "butter", name: "Масло сливочное 82.5%", cat: "Молочное", kcal: 748, p: 0.5, f: 82.5, c: 0.8 },
  { id: "cream10", name: "Сливки 10%", cat: "Молочное", kcal: 118, p: 2.7, f: 10, c: 4.5 },
  { id: "cream20", name: "Сливки 20%", cat: "Молочное", kcal: 205, p: 2.8, f: 20, c: 3.7 },
  { id: "glaze-curd", name: "Сырок глазированный", cat: "Молочное", kcal: 407, p: 8, f: 27, c: 32 },
  { id: "condensed", name: "Сгущёнка", cat: "Молочное", kcal: 320, p: 7.2, f: 8.5, c: 56 },
  { id: "condensed0", name: "Сгущёнка без сахара", cat: "ЗОЖ", kcal: 75, p: 6, f: 2, c: 8 },

  { id: "cheese", name: "Сыр твёрдый", cat: "Сыры", kcal: 356, p: 25, f: 27, c: 0 },
  { id: "cheese-ru", name: "Сыр российский 45%", cat: "Сыры", kcal: 337, p: 23, f: 28, c: 0 },
  { id: "cheese-nl", name: "Сыр голландский", cat: "Сыры", kcal: 352, p: 26, f: 27, c: 0 },
  { id: "cheese-posh", name: "Сыр пошехонский", cat: "Сыры", kcal: 350, p: 26, f: 26.5, c: 0 },
  { id: "tilsiter", name: "Сыр тильзитер", cat: "Сыры", kcal: 337, p: 25, f: 24, c: 0 },
  { id: "mozzarella", name: "Моцарелла", cat: "Сыры", kcal: 280, p: 22, f: 17, c: 2 },
  { id: "parmesan", name: "Пармезан", cat: "Сыры", kcal: 392, p: 36, f: 28, c: 0 },
  { id: "burrata", name: "Буррата", cat: "Сыры", kcal: 250, p: 14, f: 20, c: 2 },
  { id: "stracciatella", name: "Страчателла", cat: "Сыры", kcal: 247, p: 13, f: 21, c: 1.5 },
  { id: "brynza", name: "Брынза", cat: "Сыры", kcal: 260, p: 18, f: 20, c: 0 },
  { id: "suluguni", name: "Сулугуни", cat: "Сыры", kcal: 290, p: 20, f: 22, c: 0.5 },
  { id: "adyghe", name: "Сыр адыгейский", cat: "Сыры", kcal: 264, p: 20, f: 20, c: 1.5 },
  { id: "cheese-sausage", name: "Сыр колбасный", cat: "Сыры", kcal: 275, p: 23, f: 19, c: 2 },
  { id: "cottage-cheese-grain", name: "Творожное зерно в сливках", cat: "Молочное", kcal: 155, p: 12, f: 8, c: 8 },

  { id: "oats", name: "Овсянка (сухая)", cat: "Крупы", kcal: 389, p: 13, f: 6.2, c: 66 },
  { id: "oats-cook", name: "Каша овсяная на воде", cat: "Крупы", kcal: 88, p: 3, f: 1.7, c: 15 },
  { id: "oats-milk", name: "Каша рисовая молочная", cat: "Готовая еда", kcal: 97, p: 2.5, f: 3.2, c: 15 },
  { id: "oats-quick", name: "Каша быстрого приготовления", cat: "Крупы", kcal: 370, p: 11, f: 6, c: 67 },
  { id: "buckwheat", name: "Гречка (сухая)", cat: "Крупы", kcal: 343, p: 13, f: 3.4, c: 72 },
  { id: "buckwheat-cook", name: "Гречка варёная", cat: "Крупы", kcal: 110, p: 4.2, f: 1.1, c: 21 },
  { id: "rice", name: "Рис белый (сухой)", cat: "Крупы", kcal: 365, p: 7, f: 0.6, c: 79 },
  { id: "rice-cook", name: "Рис варёный", cat: "Крупы", kcal: 116, p: 2.2, f: 0.5, c: 25 },
  { id: "riceb", name: "Рис бурый (сухой)", cat: "Крупы", kcal: 362, p: 7.5, f: 2.7, c: 76 },
  { id: "quinoa", name: "Киноа (сухая)", cat: "Крупы", kcal: 368, p: 14, f: 6, c: 64 },
  { id: "bulgur", name: "Булгур (сухой)", cat: "Крупы", kcal: 342, p: 12, f: 1.3, c: 76 },
  { id: "pasta", name: "Макароны (сухие)", cat: "Крупы", kcal: 371, p: 13, f: 1.5, c: 75 },
  { id: "pasta-cook", name: "Макароны варёные", cat: "Крупы", kcal: 135, p: 5, f: 0.5, c: 27 },
  { id: "pearl", name: "Перловка варёная", cat: "Крупы", kcal: 109, p: 3.1, f: 0.4, c: 22 },
  { id: "millet", name: "Пшено (сухое)", cat: "Крупы", kcal: 348, p: 11.5, f: 3.3, c: 69 },
  { id: "semolina", name: "Манка (сухая)", cat: "Крупы", kcal: 328, p: 10, f: 1, c: 67 },
  { id: "lentil", name: "Чечевица варёная", cat: "Крупы", kcal: 116, p: 9, f: 0.4, c: 20 },
  { id: "beans", name: "Фасоль варёная", cat: "Крупы", kcal: 123, p: 8.2, f: 0.5, c: 21 },
  { id: "peas", name: "Горох варёный", cat: "Крупы", kcal: 60, p: 6, f: 0.4, c: 9 },
  { id: "cornflakes", name: "Хлопья кукурузные", cat: "Крупы", kcal: 363, p: 6.7, f: 2.8, c: 84 },
  { id: "muesli", name: "Мюсли с фруктами", cat: "Крупы", kcal: 352, p: 9, f: 6, c: 64 },
  { id: "flour", name: "Мука пшеничная", cat: "Крупы", kcal: 342, p: 10, f: 1.1, c: 70 },

  { id: "potato", name: "Картофель", cat: "Овощи", kcal: 77, p: 2, f: 0.1, c: 17 },
  { id: "potato-boil", name: "Картофель отварной", cat: "Овощи", kcal: 82, p: 2, f: 0.4, c: 16 },
  { id: "potato-fry", name: "Картофель жареный", cat: "Овощи", kcal: 192, p: 2.8, f: 9.5, c: 23 },
  { id: "potato-mash", name: "Пюре картофельное", cat: "Готовая еда", kcal: 106, p: 2, f: 4.2, c: 15 },
  { id: "broccoli", name: "Брокколи", cat: "Овощи", kcal: 34, p: 2.8, f: 0.4, c: 7 },
  { id: "cauliflower", name: "Цветная капуста", cat: "Овощи", kcal: 30, p: 2.5, f: 0.3, c: 5.4 },
  { id: "cucumber", name: "Огурец", cat: "Овощи", kcal: 15, p: 0.8, f: 0.1, c: 2.5 },
  { id: "pickle", name: "Огурец солёный", cat: "Овощи", kcal: 11, p: 0.8, f: 0.1, c: 1.7 },
  { id: "tomato", name: "Помидор", cat: "Овощи", kcal: 18, p: 0.9, f: 0.2, c: 3.9 },
  { id: "cherry", name: "Томаты черри", cat: "Овощи", kcal: 15, p: 0.9, f: 0.2, c: 2.7 },
  { id: "carrot", name: "Морковь", cat: "Овощи", kcal: 41, p: 0.9, f: 0.2, c: 10 },
  { id: "carrot-kor", name: "Морковь по-корейски", cat: "Готовая еда", kcal: 134, p: 1.2, f: 10, c: 9 },
  { id: "cabbage", name: "Капуста белокочанная", cat: "Овощи", kcal: 25, p: 1.3, f: 0.1, c: 6 },
  { id: "sauerkraut", name: "Капуста квашеная", cat: "Овощи", kcal: 19, p: 1.8, f: 0.1, c: 3 },
  { id: "pepper", name: "Перец болгарский", cat: "Овощи", kcal: 27, p: 1, f: 0.3, c: 5.3 },
  { id: "spinach", name: "Шпинат", cat: "Овощи", kcal: 23, p: 2.9, f: 0.4, c: 3.6 },
  { id: "salad", name: "Салат листовой", cat: "Овощи", kcal: 16, p: 1.5, f: 0.2, c: 2.3 },
  { id: "avocado", name: "Авокадо", cat: "Овощи", kcal: 160, p: 2, f: 15, c: 9 },
  { id: "onion", name: "Лук репчатый", cat: "Овощи", kcal: 47, p: 1.4, f: 0, c: 10 },
  { id: "garlic", name: "Чеснок", cat: "Овощи", kcal: 149, p: 6.5, f: 0.5, c: 30 },
  { id: "beet", name: "Свёкла", cat: "Овощи", kcal: 43, p: 1.6, f: 0.2, c: 9 },
  { id: "zucchini", name: "Кабачок", cat: "Овощи", kcal: 24, p: 0.6, f: 0.3, c: 4.6 },
  { id: "eggplant", name: "Баклажан", cat: "Овощи", kcal: 24, p: 1.2, f: 0.1, c: 4.5 },
  { id: "corn", name: "Кукуруза консервированная", cat: "Овощи", kcal: 58, p: 2.2, f: 0.4, c: 11 },
  { id: "peas-can", name: "Горошек зелёный", cat: "Овощи", kcal: 40, p: 3.6, f: 0.2, c: 6.5 },
  { id: "olives", name: "Оливки", cat: "Овощи", kcal: 115, p: 0.8, f: 10.7, c: 6.3 },

  { id: "apple", name: "Яблоко", cat: "Фрукты", kcal: 52, p: 0.3, f: 0.2, c: 14 },
  { id: "banana", name: "Банан", cat: "Фрукты", kcal: 89, p: 1.1, f: 0.3, c: 23 },
  { id: "orange", name: "Апельсин", cat: "Фрукты", kcal: 47, p: 0.9, f: 0.1, c: 12 },
  { id: "mandarin", name: "Мандарин", cat: "Фрукты", kcal: 53, p: 0.8, f: 0.2, c: 13 },
  { id: "pear", name: "Груша", cat: "Фрукты", kcal: 57, p: 0.4, f: 0.1, c: 15 },
  { id: "grapes", name: "Виноград", cat: "Фрукты", kcal: 65, p: 0.6, f: 0.2, c: 17 },
  { id: "kiwi", name: "Киви", cat: "Фрукты", kcal: 61, p: 1.1, f: 0.5, c: 15 },
  { id: "persimmon", name: "Хурма", cat: "Фрукты", kcal: 66, p: 0.5, f: 0.3, c: 15 },
  { id: "plum", name: "Слива", cat: "Фрукты", kcal: 46, p: 0.7, f: 0.3, c: 10 },
  { id: "peach", name: "Персик", cat: "Фрукты", kcal: 39, p: 0.9, f: 0.1, c: 9.5 },
  { id: "watermelon", name: "Арбуз", cat: "Фрукты", kcal: 30, p: 0.6, f: 0.1, c: 7.5 },
  { id: "melon", name: "Дыня", cat: "Фрукты", kcal: 35, p: 0.6, f: 0.3, c: 7.4 },
  { id: "berries", name: "Ягоды микс", cat: "Фрукты", kcal: 43, p: 0.7, f: 0.3, c: 9 },
  { id: "blueberry", name: "Голубика", cat: "Фрукты", kcal: 57, p: 0.7, f: 0.3, c: 14 },
  { id: "strawberry", name: "Клубника", cat: "Фрукты", kcal: 32, p: 0.8, f: 0.4, c: 7.5 },
  { id: "cherry-fruit", name: "Черешня", cat: "Фрукты", kcal: 50, p: 1.1, f: 0.4, c: 12 },
  { id: "lemon", name: "Лимон", cat: "Фрукты", kcal: 29, p: 0.9, f: 0.1, c: 3 },

  { id: "bread", name: "Хлеб цельнозерновой", cat: "Хлеб", kcal: 247, p: 13, f: 4.2, c: 41 },
  { id: "whitebread", name: "Батон нарезной", cat: "Хлеб", kcal: 264, p: 7.5, f: 3, c: 51 },
  { id: "borodino", name: "Хлеб бородинский", cat: "Хлеб", kcal: 208, p: 6.9, f: 1.3, c: 40 },
  { id: "rye", name: "Хлеб ржаной", cat: "Хлеб", kcal: 201, p: 6.6, f: 1.2, c: 41 },
  { id: "bran-bread", name: "Хлеб с отрубями", cat: "Хлеб", kcal: 227, p: 7.5, f: 1.3, c: 45 },
  { id: "grain-bread", name: "Хлеб зерновой", cat: "Хлеб", kcal: 274, p: 9.2, f: 6.6, c: 44 },
  { id: "toast-bread", name: "Хлеб тостовый", cat: "Хлеб", kcal: 266, p: 8, f: 3.5, c: 50 },
  { id: "lavash", name: "Лаваш тонкий", cat: "Хлеб", kcal: 275, p: 9, f: 1.2, c: 56 },
  { id: "pita", name: "Пита", cat: "Хлеб", kcal: 275, p: 9, f: 1.2, c: 55 },
  { id: "baguette", name: "Багет", cat: "Хлеб", kcal: 262, p: 8, f: 1, c: 53 },
  { id: "bread-crisp", name: "Хлебцы", cat: "Хлеб", kcal: 310, p: 10, f: 2.5, c: 62 },
  { id: "sushki", name: "Сушки", cat: "Хлеб", kcal: 330, p: 11, f: 1.3, c: 70 },
  { id: "suhari", name: "Сухари", cat: "Хлеб", kcal: 331, p: 11, f: 1.3, c: 72 },

  { id: "syrniki", name: "Сырники", cat: "Готовая еда", kcal: 220, p: 13, f: 8, c: 22 },
  { id: "zapekanka", name: "Запеканка творожная", cat: "Готовая еда", kcal: 199, p: 18, f: 5.4, c: 20 },
  { id: "olivie", name: "Салат оливье", cat: "Готовая еда", kcal: 198, p: 5.5, f: 16, c: 8 },
  { id: "caesar", name: "Салат цезарь", cat: "Готовая еда", kcal: 190, p: 9, f: 13, c: 8 },
  { id: "vinegret", name: "Винегрет", cat: "Готовая еда", kcal: 76, p: 1.6, f: 4.5, c: 7 },
  { id: "borscht", name: "Борщ с курицей", cat: "Готовая еда", kcal: 49, p: 3.2, f: 2.1, c: 4.3 },
  { id: "soup-chicken", name: "Суп куриный с лапшой", cat: "Готовая еда", kcal: 45, p: 3.5, f: 1.5, c: 4.5 },
  { id: "okroshka", name: "Окрошка на кефире", cat: "Готовая еда", kcal: 57, p: 3.5, f: 2.5, c: 5 },
  { id: "pelmeni", name: "Пельмени", cat: "Заморозка", kcal: 245, p: 12, f: 12, c: 22 },
  { id: "vareniki-curd", name: "Вареники с творогом", cat: "Заморозка", kcal: 225, p: 10, f: 4.5, c: 37 },
  { id: "vareniki-potato", name: "Вареники с картофелем", cat: "Заморозка", kcal: 165, p: 5, f: 3.5, c: 28 },
  { id: "blini-meat", name: "Блинчики с мясом", cat: "Заморозка", kcal: 232, p: 9, f: 12, c: 22 },
  { id: "blini-curd", name: "Блинчики с творогом", cat: "Заморозка", kcal: 198, p: 10, f: 7, c: 23 },
  { id: "dumpling", name: "Котлеты домашние замороженные", cat: "Заморозка", kcal: 236, p: 12, f: 16, c: 10 },
  { id: "pizza", name: "Пицца пепперони", cat: "Заморозка", kcal: 266, p: 11, f: 10, c: 33 },
  { id: "khachapuri", name: "Хачапури с сыром", cat: "Готовая еда", kcal: 335, p: 10, f: 20, c: 29 },
  { id: "sandwich-ham", name: "Сэндвич с ветчиной и сыром", cat: "Готовая еда", kcal: 255, p: 12, f: 12, c: 24 },
  { id: "onigiri", name: "Онигири", cat: "Готовая еда", kcal: 155, p: 5, f: 3, c: 27 },
  { id: "roll", name: "Ролл калифорния", cat: "Готовая еда", kcal: 176, p: 7, f: 7, c: 21 },
  { id: "croissant", name: "Круассан", cat: "Выпечка", kcal: 406, p: 8, f: 21, c: 46 },
  { id: "donut", name: "Пончик / донат", cat: "Выпечка", kcal: 417, p: 5, f: 24, c: 47 },
  { id: "puff-ham", name: "Слойка с ветчиной и сыром", cat: "Выпечка", kcal: 370, p: 8, f: 26, c: 27 },
  { id: "cheburek", name: "Чебурек", cat: "Выпечка", kcal: 290, p: 9, f: 17, c: 24 },
  { id: "pirozhok-cabbage", name: "Пирожок с капустой", cat: "Выпечка", kcal: 220, p: 5, f: 8, c: 32 },

  { id: "olive", name: "Масло оливковое", cat: "Жиры", kcal: 884, p: 0, f: 100, c: 0 },
  { id: "oil", name: "Масло подсолнечное", cat: "Жиры", kcal: 884, p: 0, f: 100, c: 0 },
  { id: "mayo", name: "Майонез 67%", cat: "Соусы", kcal: 624, p: 0.3, f: 67, c: 2.6 },
  { id: "mayo-light", name: "Майонез лёгкий", cat: "Соусы", kcal: 250, p: 0.5, f: 25, c: 5 },
  { id: "ketchup", name: "Кетчуп", cat: "Соусы", kcal: 112, p: 1.8, f: 0.1, c: 26 },
  { id: "mustard", name: "Горчица", cat: "Соусы", kcal: 143, p: 6, f: 6, c: 16 },
  { id: "adjika", name: "Аджика", cat: "Соусы", kcal: 59, p: 1, f: 0.5, c: 12 },
  { id: "nuts", name: "Орехи грецкие", cat: "Жиры", kcal: 654, p: 15, f: 65, c: 14 },
  { id: "almond", name: "Миндаль", cat: "Жиры", kcal: 579, p: 21, f: 50, c: 22 },
  { id: "peanut", name: "Арахис жареный", cat: "Жиры", kcal: 640, p: 26, f: 52, c: 17 },
  { id: "peanut-butter", name: "Арахисовая паста", cat: "Жиры", kcal: 588, p: 25, f: 50, c: 20 },
  { id: "seeds", name: "Семечки подсолнечника", cat: "Жиры", kcal: 601, p: 21, f: 53, c: 11 },
  { id: "nori-chips", name: "Нори-чипсы", cat: "ЗОЖ", kcal: 350, p: 25, f: 3, c: 40 },

  { id: "protein", name: "Протеин сывороточный", cat: "ЗОЖ", kcal: 380, p: 75, f: 5, c: 8 },
  { id: "bar", name: "Протеиновый батончик", cat: "ЗОЖ", kcal: 360, p: 30, f: 12, c: 30, unit: "шт", unitG: 60 },
  { id: "pastila", name: "Пастила без сахара", cat: "ЗОЖ", kcal: 220, p: 0.5, f: 0.2, c: 54 },
  { id: "smoothie", name: "Смузи фруктовый", cat: "Напитки", kcal: 52, p: 0.6, f: 0, c: 12.5 },

  { id: "coffee", name: "Кофе без сахара", cat: "Напитки", kcal: 2, p: 0.1, f: 0, c: 0 },
  { id: "latte", name: "Латте Пятёрочка Кафе", cat: "Напитки", kcal: 58, p: 2.8, f: 2.6, c: 5.5 },
  { id: "cappuccino", name: "Капучино Пятёрочка Кафе", cat: "Напитки", kcal: 46, p: 2.4, f: 2.2, c: 4 },
  { id: "tea", name: "Чай без сахара", cat: "Напитки", kcal: 1, p: 0, f: 0, c: 0 },
  { id: "kvass", name: "Квас", cat: "Напитки", kcal: 27, p: 0.2, f: 0, c: 5.2 },
  { id: "cola", name: "Газировка сладкая", cat: "Напитки", kcal: 42, p: 0, f: 0, c: 10.6 },
  { id: "cola-zero", name: "Газировка без сахара", cat: "Напитки", kcal: 1, p: 0, f: 0, c: 0 },
  { id: "juice", name: "Сок апельсиновый", cat: "Напитки", kcal: 45, p: 0.7, f: 0.2, c: 10 },
  { id: "juice-apple", name: "Сок яблочный", cat: "Напитки", kcal: 46, p: 0.4, f: 0.1, c: 11 },
  { id: "compote", name: "Компот", cat: "Напитки", kcal: 60, p: 0.2, f: 0, c: 15 },
  { id: "water", name: "Вода питьевая", cat: "Напитки", kcal: 0, p: 0, f: 0, c: 0 },

  { id: "honey", name: "Мёд", cat: "Сладости", kcal: 304, p: 0.3, f: 0, c: 82 },
  { id: "chocolate", name: "Шоколад тёмный", cat: "Сладости", kcal: 546, p: 5, f: 31, c: 61 },
  { id: "chocolate-milk", name: "Шоколад молочный", cat: "Сладости", kcal: 535, p: 7, f: 30, c: 60 },
  { id: "sugar", name: "Сахар", cat: "Сладости", kcal: 387, p: 0, f: 0, c: 100 },
  { id: "icecream", name: "Пломбир в стаканчике", cat: "Сладости", kcal: 207, p: 3.5, f: 11, c: 24 },
  { id: "cookies", name: "Печенье сахарное", cat: "Сладости", kcal: 417, p: 7.5, f: 12, c: 70 },
  { id: "oat-cookies", name: "Печенье овсяное", cat: "Сладости", kcal: 437, p: 6.5, f: 14, c: 71 },
  { id: "wafers", name: "Вафли", cat: "Сладости", kcal: 425, p: 3.2, f: 14, c: 65 },
  { id: "zefir", name: "Зефир", cat: "Сладости", kcal: 304, p: 0.8, f: 0.1, c: 80 },
  { id: "marmalade", name: "Мармелад", cat: "Сладости", kcal: 296, p: 0.1, f: 0.1, c: 76 },
  { id: "jam", name: "Варенье", cat: "Сладости", kcal: 250, p: 0.3, f: 0.1, c: 65 },
  { id: "chips", name: "Чипсы картофельные", cat: "Сладости", kcal: 510, p: 6, f: 30, c: 53 },
  { id: "popcorn", name: "Попкорн", cat: "Сладости", kcal: 375, p: 8, f: 5, c: 74 }
];
